name: Build Magisk Module

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Module Zip
        run: |
          cd Magisk_Module_Source
          zip -r9 ../POCO_M5_Incall_Audio_Fix.zip *
          cd ..

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: POCO_M5_Incall_Audio_Fix
          path: POCO_M5_Incall_Audio_Fix.zip

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: POCO_M5_Incall_Audio_Fix.zip
